### ISSUE TITLE
No preview show up, exceptions thrown in console

### ISSUE THREAD

**Issue by zethriller** [CurtisDS/sd-model-preview-xd#30]
Using commit de2146ec in automatic1111 v1.4.1

When selecting a model, or anything else from the dropdowns in the model previews tab, an exception is shown:
```
Traceback (most recent call last):
  File "C:\automatic1111\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\automatic1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "C:\automatic1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\automatic1111\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\automatic1111\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\automatic1111\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\automatic1111\stable-diffusion-webui\extensions\sd-model-preview-xd\scripts\modelpreview.py", line 811, in show_model_preview
    return show_preview(modelname, get_checkpoints_dirs(), "checkpoints")
  File "C:\automatic1111\stable-diffusion-webui\extensions\sd-model-preview-xd\scripts\modelpreview.py", line 842, in show_preview
    html_code, found_md_file, found_prompts_file, found_txt_file = search_and_display_previews(name, paths)
  File "C:\automatic1111\stable-diffusion-webui\extensions\sd-model-preview-xd\scripts\modelpreview.py", line 587, in search_and_display_previews
    civitai_pattern = re.compile(r'^.*' + re.escape(model_name) + r'.*(?i:\.' + civitai_generic_pattern + r')$')
TypeError: can only concatenate str (not "re.Pattern") to str
```
`civitai_generic_pattern` should be `civitai_ext_pattern` ? (I barely know anything about python...)

But if i change that, another one pops up:
```
Traceback (most recent call last):
  File "C:\automatic1111\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\automatic1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "C:\automatic1111\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\automatic1111\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\automatic1111\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\automatic1111\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\automatic1111\stable-diffusion-webui\extensions\sd-model-preview-xd\scripts\modelpreview.py", line 812, in show_model_preview
    return show_preview(modelname, get_checkpoints_dirs(), "checkpoints")
  File "C:\automatic1111\stable-diffusion-webui\extensions\sd-model-preview-xd\scripts\modelpreview.py", line 843, in show_preview
    html_code, found_md_file, found_prompts_file, found_txt_file = search_and_display_previews(name, paths)
  File "C:\automatic1111\stable-diffusion-webui\extensions\sd-model-preview-xd\scripts\modelpreview.py", line 682, in search_and_display_previews
    civitai_info_html = create_civitai_info_html(file_path)
  File "C:\automatic1111\stable-diffusion-webui\extensions\sd-model-preview-xd\scripts\modelpreview.py", line 460, in create_civitai_info_html
    meta_list_items = "\n".join([f"<li><strong>{key}:</strong> {meta_data.get(key,'')}</li>" for key in meta_data])
TypeError: 'NoneType' object is not iterable
```

Thank you

**Comment by CurtisDS** [comment]
The first error was a typo that only affected the loose naming pattern. Sorry about that. You did correct it properly it looks like.

The second error looks to be because one of the images doesn't have meta data. I only have one sample JSON to work with so there may be edge cases that cause issues.

I should have both issues fixed in the next commit.

**Comment by CurtisDS** [comment]
I'm going to close this as I have tested a few possible edge cases now with empty meta data and they don't error out. But if you're still having issues comment and I'll reopen the issue.
