### ISSUE TITLE
Model Preview stopped working

### ISSUE THREAD

**Issue by dichter** [CurtisDS/sd-model-preview-xd#44]
Hi I've just solved a problem that I had for a couple of weeks. The Model Preview have stopped working, 
there was a following traceback during webui startup:

```
*** Error loading script: modelpreview.py
    Traceback (most recent call last):
      File "/Users/ge/stable-diffusion-webui/modules/scripts.py", line 515, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/ge/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 940, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/Users/ge/stable-diffusion-webui/extensions/sd-model-preview-xd/scripts/modelpreview.py", line 14, in <module>
        from lxml.html.clean import Cleaner
      File "/Users/ge/stable-diffusion-webui/venv-torch-nightly/lib/python3.11/site-packages/lxml/html/clean.py", line 18, in <module>
        raise ImportError(
    ImportError: lxml.html.clean module is now a separate project lxml_html_clean.
    Install lxml[html_clean] or lxml_html_clean directly.

---
```

The problem could be solved by running 
 
`pip install --upgrade lxml_html_clean`

I am not sure what needs to be changed in the code to have this dependency updated.

**Comment by CurtisDS** [comment]
hmmm... lxml was installed by default. With them stripping out the clean module into a separate project, I guess I have to add it as an explicit requirement.

Oddly I havent had this error myself. Maybe it depends on the version of python. But I'll look at adding a requirement to the extension.

**Comment by CurtisDS** [comment]
3eb6ee5b88a23267ae02b6bce41b15cb1b9f979b added the module to the install for the extension which should prevent the error
